### ISSUE TITLE
installing cdk8s on centos7

### ISSUE THREAD

**Issue by sumit180591** [dungahk/awesome-cdk8s#5]
Hello Guys,

While installing cdk8s on centos 7 I encountered with following error :-

Bash completion has been installed to:
  /home/linuxbrew/.linuxbrew/etc/bash_completion.d
==> Summary
  /home/linuxbrew/.linuxbrew/Cellar/node/14.3.0: 4,658 files, 69.2MB
==> Installing cdk8s
Error: An exception occurred within a child process:
  RuntimeError: npm failed to pack /tmp/cdk8s-20200526-77213-i9fl4r/package

**and while installing with npm I got this error :-**
[root@kubemaster1 ~]# npm install -g cdk8s-cli
/usr/lib
└── (empty)

npm ERR! Linux 3.10.0-1062.4.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "cdk8s-cli"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! path /usr/lib/node_modules/.staging/@babel/runtime-77045e9f
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/usr/lib/node_modules/.staging/@babel/runtime-77045e9f' -> '/usr/lib/node_modules/cdk8s-cli/node_modules/cdk8s/node_modules/@babel/runtime'
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/lib/node_modules/.staging/@babel/runtime-77045e9f' -> '/usr/lib/node_modules/cdk8s-cli/node_modules/cdk8s/node_modules/@babel/runtime'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
npm ERR! code 1

Reference link :-
https://github.com/awslabs/cdk8s/blob/master/docs/getting-started/python.md

**Comment by emersonreisdev** [comment]
Thanks for raising this, @sumit180591 !

Would you mind raising it on the official repo? This repository is only for aggregating good resources about cdk8s.

If you raise it on https://github.com/awslabs/cdk8s they will be able to help you out!
